// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_e8kuISbtYTS04ptgDaa-C34z0g3RKJg',
    appId: '1:8082473065:android:fb802554220b3edab822f8',
    messagingSenderId: '8082473065',
    projectId: 'fitness-c3f28',
    storageBucket: 'fitness-c3f28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhaB2rSnnEPvifu1MQLnwPWDCq2OtTNfE',
    appId: '1:8082473065:ios:3c35b5c7361f2fbbb822f8',
    messagingSenderId: '8082473065',
    projectId: 'fitness-c3f28',
    storageBucket: 'fitness-c3f28.firebasestorage.app',
    iosBundleId: 'com.example.walkscape',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhaB2rSnnEPvifu1MQLnwPWDCq2OtTNfE',
    appId: '1:8082473065:ios:3c35b5c7361f2fbbb822f8',
    messagingSenderId: '8082473065',
    projectId: 'fitness-c3f28',
    storageBucket: 'fitness-c3f28.firebasestorage.app',
    iosBundleId: 'com.example.walkscape',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq8Ua2mpwo7XwqOliCCFUOoKzCv9buKTg',
    appId: '1:8082473065:web:56b487ec7661bd07b822f8',
    messagingSenderId: '8082473065',
    projectId: 'fitness-c3f28',
    authDomain: 'fitness-c3f28.firebaseapp.com',
    storageBucket: 'fitness-c3f28.firebasestorage.app',
    measurementId: 'G-HMM5BT8MT3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq8Ua2mpwo7XwqOliCCFUOoKzCv9buKTg',
    appId: '1:8082473065:web:56b487ec7661bd07b822f8',
    messagingSenderId: '8082473065',
    projectId: 'fitness-c3f28',
    authDomain: 'fitness-c3f28.firebaseapp.com',
    storageBucket: 'fitness-c3f28.firebasestorage.app',
    measurementId: 'G-HMM5BT8MT3',
  );

}